docs/articles/test-executions.md

docs: test workflow execution

---

docs/articles/test-workflows.md

feat: test workflow status

---

package-lock.json
package.json

update Docusaurus to 3.4.0

---

docs/articles/webhooks.mdx

This PR...
- updates docs for disabling webhooks - see https://github.com/kubeshop/testkube/pull/5560
-

feat: [TKC-1948] disable webhooks on resources

---

docs/articles/test-workflows-content.md

- add `workingDir` tip to the Test Workflows - Content
-

feat: add tip about workingDir in content

---

docs/articles/metrics.md

docs: twe metrics

---

docs/articles/core-concepts.md
docs/index.mdx

fixed link to core concepts from welcome page

---

docs/index.mdx

minor changes to improve flow/readability!?

---

docs/articles/test-workflow-migration.md
sidebars.js

docs: test workflow migration

---

docs/articles/istio.md
docs/articles/vault.md
sidebars.js

This PR...
- Guide to working with Vault.
- Migrating Guide to working with Istio.
-

docs: vault docs & migrating istio docs

---

docs/articles/install/3-install-with-helm.md
docs/articles/install/4-advanced-install.md
docs/articles/install/multi-cluster.md

Fix helm config

---

docusaurus.config.js

updated navbar with links to slack, getting-started and contact

---

docs/articles/metrics.md

docs: metrics

---

docs/articles/test-workflow-templates.md
sidebars.js

simplified Workflow Templates docs to be single doc under Test Workflows

---

docs/articles/test-triggers.mdx

docs: disable test trigger flag

---

docs/index.mdx
docusaurus.config.js

updated links and wording

---

.github/CODEOWNERS
docs/articles/test-workflows.md

fix: yaml indenting in WF postman example

---

docs/articles/tekton.mdx
sidebars.js

This PR...
- Testkube Tekton integration doc
-
- [ Yes ] tested locally
- [ No ] added new dependencies
- [ Yes ] updated the docs
- [ Yes ] added a test workflow

Added tekton doc

---

docs/articles/install/3-install-with-helm.md
docs/articles/install/4-advanced-install.md

docs: update installation guide

---

docs/articles/test-workflows-services.md
docs/articles/test-workflows.md
docs/workflows/distributed-jmeter-workflow.md
docs/workflows/simple-jmeter-workflow.md
redirects.js

updated jmeter image in examples and added redirect

---

docs/articles/slack-integration.md

docs: Add Webhooks Blog link to Slack Integration page

---

docs/articles/webhooks.mdx
docs/cli/testkube_create_webhook.md
docs/cli/testkube_update_webhook.md

fix: new webhook events

---

docs/articles/github-actions.mdx
docs/articles/test-workflows.md

fix: github action version

---

docs/articles/examples/overview.mdx
sidebars.js

added menu links to various learn docs

---

docs/articles/private-ca.md

docs: update private CA docs

---

docs/articles/install/s3-storage.md

docs: fix s3 integration

---

README.md
docs/articles/crds/executor.testkube.io-v1.md
docs/articles/crds/tests.testkube.io-v1.md
docs/articles/crds/tests.testkube.io-v2.md
docs/articles/crds/tests.testkube.io-v3.md
docs/articles/testkube-dashboard-workflows-templates.md
docs/cli/testkube_completion_fish.md
docs/cli/testkube_completion_powershell.md
docusaurus.config.js
package-lock.json
package.json
src/theme/DocCard/index.js
src/theme/NotFound/index.js

updated docusaurus, search-config, cli-docs

---

docs/articles/test-workflows-expressions.md

fix: organization/environment/dashboard variables definition

---

redirects.js

fixed in-app documentation url redirect

---

docs/articles/integrations.md
docs/articles/testkube-dashboard-workflows-overview.md
docs/articles/tutorial/2-quickstart.mdx

improved quickstart and fixed some links

---

docs/articles/install/0-overview.md
docs/articles/install/6-deployment-architectures.md
docs/articles/install/7-faq.md
sidebars.js

minor adjustements to installation docs

---

docs/articles/webhooks.mdx

Enhance webhook docs: Add guide for API server env variables usage

---

docs/articles/webhooks.mdx

fixed bracket escaping in example and added corresponding note

---

docs/articles/test-workflows-expressions.md

feat: labels vars

---

docs/articles/testkube-dashboard-explore.md
docs/index.mdx
src/components/TwoColumns/TwoColumns.module.css
src/components/TwoColumns/index.js

To docs welcome page.
This PR...
-
-

docs: Add Getting Started Video

---

docs/articles/test-workflows-examples-configuration.md
docs/articles/test-workflows-expressions.md

docs: secret func

---

docs/articles/slack-integration.md

- fix typo in the Custom Payload for Slack integration
- add Custom Payload example for legacy integration (Test Workflows, Tests and Test Suites)
-

fix: update the Custom Payload for Slack integration

---

docs/articles/slack-integration.md

- add note for notifying about failed tests
- fix the event names used for Test Workflows
-

fix: add notes for handling Test Failures in Slack integration

---

docs/articles/architecture.md
docs/articles/argocd-integration.mdx
docs/articles/cicd-overview.mdx
docs/articles/defining-tests.md
docs/articles/grafana.mdx
docs/articles/install/4-advanced-install.md
docs/articles/install/6-deployment-architectures.md
docs/articles/install/7-faq.md
docs/articles/install/multi-cluster.md
docs/articles/install/standalone-agent.md
docs/articles/secrets-disable-creation.md
docs/articles/slack-integration.md
docs/articles/tekton.mdx
docs/articles/telemetry.md
docs/articles/test-insights.md
docs/articles/test-workflows-artifacts.md
docs/articles/test-workflows-expressions.md
docs/articles/troubleshooting-tests.md
docs/articles/tutorial/1-introduction.md
docs/articles/tutorial/2-quickstart.mdx
docs/articles/webhooks.mdx
docs/testkube-pro/articles/architecture.md

added missing mentions of Tekton and ArgoCD

---

docs/articles/deprecations.md

Needed some editing.
This PR...
-
-

docs: Update deprecations.md

---

docs/articles/install/3-install-with-helm.md

docs: add images for components

---

docs/articles/test-workflows-job-and-pod.md

added info on global templates

---

docs/articles/test-workflow-templates.md
docs/articles/test-workflows-job-and-pod.md

moved global template section to Workflow Template doc..

---

docs/articles/test-workflows-job-and-pod.md

fix: securityContext snippet

---

docs/articles/argorollouts-integration.md

added links and more details..

---

docs/cli/testkube_pro.md
docs/cli/testkube_pro_docker.md
docs/cli/testkube_set_context.md
docs/cli/testkube_upgrade.md

docs: docker cli

---

docs/articles/_cli_installation.mdx
docs/articles/cicd-overview.mdx
docs/articles/install/1-cli.mdx
docs/articles/install/2-install-with-cli.mdx
docs/testkube-pro/articles/audit-logs.md
sidebars.js

fixed links, wording, etc

---

docs/cli/testkube.md
docs/cli/testkube_docker.md
docs/cli/testkube_docker_init.md

docs: move docker command

---

docs/articles/install/4-advanced-install.md

chore: add bootstrap config team docs

---

docs/articles/deploying-from-private-registries.md

docs: update docs

---

docs/cli/testkube_docker_init.md

fix: use default agent uri docker

---

docs/articles/test-workflows-reports.md

docs: go, jest, mocha junit reports

---

docs/articles/resource-access-management.md

added blurb about RBAC

---

docs/articles/deploying-from-private-registries.md
sidebars.js

added doc on private registries

---

docs/cli/testkube_get_testworkflowexecution.md

feat: [TKC-2556] add actor filter

---

docs/articles/test-workflows.md

docs: [TKC-2726] cronjob config

---

docs/articles/argorollouts-integration.md
docs/articles/argoworkflows-integration.md
docs/articles/integrations.md
sidebars.js

added argo-workflows doc

---

docs/articles/test-workflows-expressions.md

expressions page - `secret` - typo fixed

---

docs/articles/install/4-advanced-install.md

chore: add groups scope config docs

---

docs/articles/scheduling-tests.mdx

fix: curl image

---

docs/articles/testkube-dashboard-workflow-details.md
docs/articles/testkube-dashboard-workflows-templates.md

added blurb on not being able to rename Workflows/Templates

---

docs/articles/deploying-from-private-registries.md

docs: fix global setting

---

src/theme/SearchBar/index.js

fix: searchbar placeholder

---

src/css/custom.css
src/theme/SearchBar/SearchBarFilter.js
src/theme/SearchBar/SearchbarFilter.css
src/theme/SearchBar/index.js

fix: remove search label

---

docs/articles/architecture.md
docs/articles/install/4-advanced-install.md
docs/articles/legacy-architecture.md
docs/articles/mongodb-administration.md
redirects.js
sidebars.js

feat: add mongodb TTL index docs

---

docs/articles/install/4-advanced-install.md

TKC-2763: add docs for configuring automatic storage cleanup

---

docs/articles/install/2-install-with-cli.mdx
docs/articles/migrate-from-oss.md

docs: added info about diagnostic tools

---

redirects.js

added redirect for cli uninstall

---

package-lock.json
package.json

updated to docusaurus 3.6.3

---

docs/articles/inventory/generated/agent_images.md
docs/articles/inventory/generated/bitnami-mongodb-7.0.12_linux_amd64.md
docs/articles/inventory/generated/bitnami-mongodb-7.0.12_linux_arm64.md
docs/articles/inventory/generated/cp_images.md
docs/articles/inventory/generated/minio-2024.11.7-debian-12-r1_linux_amd64.md
docs/articles/inventory/generated/minio-2024.11.7-debian-12-r1_linux_arm64.md
docs/articles/inventory/generated/testkube-operator-2.1.67_linux_amd64.md
docs/articles/inventory/generated/testkube-operator-2.1.67_linux_arm64.md

docs: upate image inventory

---

docs/articles/open-source-or-pro.md

updated oss-comparison and some wording

---

docs/articles/install/4-advanced-install.md

feat update multinamespace installation

---

docs/articles/test-workflows-job-and-pod.md

feat: [TKC-2895] pvc config

---

docs/articles/test-workflows-content.mdx

fix: typo in pulling selected files section

---

docs/articles/flux-integration.mdx

This PR...
- Flux Integration Docs
- Set using Test Workflow
- [ x] tested locally
- [ x] updated the docs

Updated flux integration doc

---

docs/articles/global-parameters-in-testkube-helm-charts.md

update docs for global image registry

---

docs/articles/test-triggers.md

feat: [TKC-3102] add new causes

---

docs/articles/test-workflows-services.mdx
docs/workflows/distributed-jmeter-workflow.md
docs/workflows/simple-jmeter-workflow.md

updated to official jmeter image in samples/docs

---

docs/articles/webhooks.mdx

docs: Sprig funcs for webhooks

---

docs/articles/install/4-advanced-install.md

fix: update executionNamespaces example in values.yaml

---

docs/articles/jira-integration.md

update JIRA integration docs

---

docs/articles/copilot-can-help.md
docs/articles/copilot-enable.md
docs/articles/copilot-is-different.md
docs/articles/copilot-on-prem-install.md
docs/articles/copilot-overview.md
sidebars.js

docs: initial copilot docs

---

docs/articles/test-workflows.md

docs: restructure the test workflows overview

---

docs/articles/integrations.md
docs/articles/jira-integration.md
docs/articles/webhooks.mdx
sidebars.js

added keptn integration and webhook-template improvements

---

docs/articles/test-triggers.md

feat: [TKC-3146] [TKC-3147] trigger parameters and regex

---

docs/articles/flux-integration.mdx
docs/articles/github-actions.mdx
docs/articles/test-workflows-content.mdx

This PR contributes to TKC-3197

chore: add github app docs

---

docs/articles/deploying-on-openshift.md

feat: update openshift doc

---

docs/articles/install/3-install-with-helm.md

update ingress docs

---

docs/articles/install/0-overview.mdx
docs/articles/install/2-install-with-cli.mdx
docs/articles/install/3-install-with-helm.md
docs/articles/tutorial/2-quickstart.mdx
docs/old/migrate-from-oss.md
docs/old/testkube-pro-on-prem/migrating-from-oss-to-pro.md

updated trial-license link and info

---

docs/articles/open-source.md

This PR...
- Testkube Open Source docs
-
- [ yes] tested locally
- [ yes] updated the docs

Add doc for Testkube Open Source demo

---

docs/articles/telemetry.md

This PR is to add Telemetry documentation needed to cover how to enable or disable it for Testkube On Prem deployments.
-
-

chore: document how to disable telemetry in testkube control plane

---

docs/index.mdx
docs/test-types/executor-playwright.mdx
docusaurus.config.js
sidebars.js

minor fixes for semrush/ahrefs

---

docs/articles/tekton.mdx

fixed incorrect ref link

---

static/robots.txt

added initial robots.txt

---

docs/articles/install/standalone-agent.md
static/robots.txt

Added new disallowed paths to robots.txt to improve SEO management. Corrected the header in standalone-agent documentation for consistency with formatting guidelines.
This PR...
-
-

Update robots.txt and fix header in standalone-agent docs

---

docs/articles/test-workflows-content.mdx
package-lock.json
package.json

Small change

---

package-lock.json
package.json

upgraded docusaurus to 3.7.0

---

docs/articles/test-workflows-services.mdx

chore: timeout definition

---

docs/articles/test-workflows-content.mdx
docs/articles/test-workflows-high-level-architecture.md
docs/articles/tutorial/2-quickstart.mdx

fix: [TKC-3449] workingDir resolution

---

docs/articles/copilot-on-prem-install.md

refactor: update copilot on-prem install page

---

docs/articles/install/4-advanced-install.md

fix invitation docs

---

docs/articles/install/multi-agent.md
docs/articles/multi-agent-runner-helm-chart.md
docs/testkube-pro/articles/agent-management.md

- docs for https://github.com/kubeshop/helm-charts/pull/1016
-

feat: add docs for specialized Runner Agent's Helm Chart

---

docs/testkube-pro/articles/environment-management.md
redirects.js

added redirect for old multi-cluster page

---

docs/articles/architecture.md

fix: license endpoint

---

docs/articles/deploying-on-openshift.md

openshift: small note

---

docs/cli/testkube-create-testworkflow.md
docs/cli/testkube-create-testworkflowtemplate.md

fix: [TKC-3569] add dry run

---

docs/articles/test-workflows-expressions.md

added execution tags to table of expression variables..

---

docs/articles/scheduling-tests.mdx
docs/articles/test-workflows.md

feat: [TKC-3694] cron timezone

---

docs/CHANGELOG.mdx
package-lock.json
sidebars.js

feat: add changelog

---

docs/changelog.mdx

chore: add a doc entry in changelog for audit logger

---

docs/articles/datadog-junit.mdx
sidebars.js

Adding documentation for Datadog junit integration 

---

docs/articles/install/2-install-with-cli.mdx
docs/articles/tutorial/2-quickstart.mdx

added note on local-user constraint for demo install

---

docs/changelog.mdx

feat: add release changelog

---

docs/articles/test-workflows-high-level-architecture.md

chore: add steps to configure integration with private aws ecr

---

docs/articles/legacy-features.md

chore: add doc on how to disable legacy test for agent

---

docs/articles/webhooks.mdx

This PR...
- added a section detailing how to manage Webhook templates 
-

Update for managing WebhookTemplate resource 

---

docs/articles/multi-agent-runner-helm-chart.md

fix: runner install

---

docs/changelog.mdx

update release version to 1.17.1

---

docs/articles/metrics.md
sidebars.js

updated metrics with groups

---

docs/changelog.mdx

chore: update changelog for v1.18.5

---

docs/changelog.mdx

chore: changelog for 1.18.7 patch release

---

docs/articles/scim.md

This PR adds guide for integrating Okta with Testkube SCIM
-
-

docs: add guide for integrating Okta with Testkube SCIM

---

docs/articles/test-triggers.md

This PR...
- reworked to clarify the old selectors
- added section about the new event selector.
-

docs: triggers docs
